Adding cloudformation to support wazuh agent
guardian/itunes-rss pull request #87
Opened 2021-04-27 15:00 UTC by frj

This PR makes some changes to the security configuration of the launch config for the apps auto scale group.

## What does this change?

This is to support enabling the Wazuh vulnerability scanner agent. For more details see:

https://github.com/guardian/security-hq/blob/main/hq/markdown/wazuh.md

The changes to the security config are as follows:

- Adding a security group to allow network connections from the agent to the Wazuh service.
- Allowing read permissions on the autoscale group to allow the wazuh agent to collect information about the ASG.

NOTE: In addition to these changes we need to update the AMI configured in the itunes-rss launch configuration to an AMI that has the Wazuh profile:

https://amigo.gutools.co.uk/recipes/ubuntu-bionic-capi

This is configured manually in the stack parameters when deploying the cloudformation template:

<img width="795" alt="Screenshot 2021-04-27 at 14 33 49" src="https://user-images.githubusercontent.com/289928/116250446-a4010d80-a765-11eb-91f9-b1f491693b7f.png">

## How to test

This change should mean the itunes-rss instances show up on the Wazuh dashboard but this is only accessible to the infosec team.

You can see the status of the wazuh agent using the following command:

ssm cmd -c "service wazuh-agent start" -t podcasts-rss,content-api,PROD -p capi

2021-04-27 15:31 UTC, JustinPinner approved these changes
`start`/`status` question aside, LGTM 👍

2021-04-27 15:31 UTC, frj commented
@JustinPinner yes good spot, too much cutting and pasting.

2021-05-19 11:47 UTC, Fweddi requested changes

2021-05-19 11:47 UTC, Fweddi commented on cloudformation.yaml
> +      - !Ref: RootRole
I made a comment in another PR on this - I believe with refs you either use `Ref:` or `!Ref` (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html). So this hybrid might cause issues. Otherwise LGTM.

2021-05-19 13:10 UTC, JustinPinner commented on cloudformation.yaml
> +        - Ref RootRole
🙄 this should have been a `!Ref`

2021-05-20 09:50 UTC, Fweddi approved these changes

2021-05-25 13:49 UTC, merged